# Generated by Django 5.0.4 on 2024-05-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_application_advertisement_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date_of_application',
            field=models.DateField(blank=True, null=True),
        ),
    ]
