# Generated by Django 5.0.4 on 2024-05-05 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_application_date_of_application'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageModel1',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('advertisement_number', models.CharField(max_length=100)),
                ('post_applied_for', models.CharField(max_length=100)),
                ('date_of_application', models.DateField()),
                ('application_number', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('GEN', 'GEN'), ('EWS', 'EWS'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('PWD', 'PWD')], max_length=10)),
                ('gender', models.CharField(max_length=20)),
                ('marital_status', models.CharField(max_length=20)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('id_proof_type', models.CharField(max_length=100)),
                ('id_proof_upload', models.FileField(upload_to='id_proofs/')),
                ('street_correspondence', models.CharField(max_length=100)),
                ('city_correspondence', models.CharField(max_length=100)),
                ('district_correspondence', models.CharField(max_length=100)),
                ('state_correspondence', models.CharField(max_length=100)),
                ('country_correspondence', models.CharField(max_length=100)),
                ('pin_correspondence', models.CharField(max_length=20)),
                ('street_permanent', models.CharField(max_length=100)),
                ('city_permanent', models.CharField(max_length=100)),
                ('district_permanent', models.CharField(max_length=100)),
                ('state_permanent', models.CharField(max_length=100)),
                ('country_permanent', models.CharField(max_length=100)),
                ('pin_permanent', models.CharField(max_length=20)),
                ('mobile_number', models.CharField(max_length=15)),
                ('alternate_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('alternate_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('landline', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='contactdetails',
            name='user',
        ),
        migrations.RemoveField(
            model_name='correspondenceaddress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='permanentaddress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='user',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='ContactDetails',
        ),
        migrations.DeleteModel(
            name='CorrespondenceAddress',
        ),
        migrations.DeleteModel(
            name='PermanentAddress',
        ),
        migrations.DeleteModel(
            name='PersonalDetails',
        ),
    ]
