# Generated by Django 5.0.4 on 2024-05-07 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_pagemodel1_marital_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageModel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phd_university', models.CharField(max_length=100)),
                ('phd_department', models.CharField(max_length=100)),
                ('phd_supervisor', models.CharField(max_length=100)),
                ('phd_join_year', models.CharField(max_length=4)),
                ('phd_defence_date', models.DateField()),
                ('phd_award_date', models.DateField()),
                ('phd_thesis_title', models.CharField(max_length=100)),
                ('pg_degree', models.CharField(max_length=100)),
                ('pg_university', models.CharField(max_length=100)),
                ('pg_branch', models.CharField(max_length=100)),
                ('pg_join_year', models.CharField(max_length=4)),
                ('pg_completion_year', models.DateField()),
                ('pg_duration', models.IntegerField()),
                ('pg_percentage_cgpa', models.CharField(max_length=100)),
                ('pg_division', models.CharField(max_length=100)),
                ('ug_degree', models.CharField(max_length=100)),
                ('ug_university', models.CharField(max_length=100)),
                ('ug_branch', models.CharField(max_length=100)),
                ('ug_join_year', models.CharField(max_length=4)),
                ('ug_completion_year', models.DateField()),
                ('ug_duration', models.IntegerField()),
                ('ug_percentage_cgpa', models.CharField(max_length=100)),
                ('ug_division', models.CharField(max_length=100)),
                ('additional_qualifications', models.JSONField(default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Page 2 Model',
                'verbose_name_plural': 'Page 2 Models',
            },
        ),
    ]
