# Generated by Django 5.0.4 on 2024-05-08 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_pagemodel2_college_class_pagemodel2_college_division_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageModel3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('organisation', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('joining_date', models.DateField()),
                ('leaving_date', models.DateField()),
                ('duration', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Page 3 Model',
                'verbose_name_plural': 'Page 3 Models',
            },
        ),
    ]
