# Generated by Django 5.0.4 on 2024-05-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_pagemodel3'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagemodel3',
            name='area_of_research',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagemodel3',
            name='area_of_specialization',
            field=models.TextField(blank=True, null=True),
        ),
    ]
