# Generated by Django 5.0.4 on 2024-05-08 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_pagemodel3_area_of_research_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageModel4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('international_journal_papers', models.IntegerField()),
                ('national_journal_papers', models.IntegerField()),
                ('international_conference_papers', models.IntegerField()),
                ('national_conference_papers', models.IntegerField()),
                ('patents', models.IntegerField()),
                ('books', models.IntegerField()),
                ('book_chapters', models.IntegerField()),
                ('google_scholar_link', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Page 4 Model',
                'verbose_name_plural': 'Page 4 Models',
            },
        ),
    ]
