# Generated by Django 5.0.4 on 2024-05-08 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_pagemodel5'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageModel6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phd_name', models.CharField(max_length=100)),
                ('phd_title', models.CharField(max_length=100)),
                ('phd_role', models.CharField(max_length=100)),
                ('phd_status', models.CharField(max_length=100)),
                ('phd_date', models.DateField()),
                ('pg_name', models.CharField(max_length=100)),
                ('pg_title', models.CharField(max_length=100)),
                ('pg_role', models.CharField(max_length=100)),
                ('pg_status', models.CharField(max_length=100)),
                ('pg_date', models.DateField()),
                ('ug_name', models.CharField(max_length=100)),
                ('ug_title', models.CharField(max_length=100)),
                ('ug_role', models.CharField(max_length=100)),
                ('ug_status', models.CharField(max_length=100)),
                ('ug_date', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
