# Generated by Django 5.0.4 on 2024-05-08 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_pagemodel6'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageModel7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_plans', models.TextField(blank=True)),
                ('teaching_plans', models.TextField(blank=True)),
                ('other_details', models.TextField(blank=True)),
                ('services_details', models.TextField(blank=True)),
                ('jour_details', models.TextField(blank=True)),
                ('conference_details', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
