# Generated by Django 5.0.4 on 2024-05-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_pagemodel7'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_papers', models.FileField(upload_to='research_papers')),
                ('phd_certificate', models.FileField(upload_to='phd_certificate')),
                ('pg_documents', models.FileField(upload_to='pg_documents')),
                ('ug_documents', models.FileField(upload_to='ug_documents')),
                ('certificate_12th', models.FileField(upload_to='certificate_12th')),
                ('certificate_10th', models.FileField(upload_to='certificate_10th')),
                ('pay_slip', models.FileField(upload_to='pay_slip')),
                ('noc_undertaking', models.FileField(upload_to='noc_undertaking')),
                ('post_phd_experience', models.FileField(upload_to='post_phd_experience')),
                ('other_documents', models.FileField(upload_to='other_documents')),
                ('signature', models.ImageField(upload_to='signature')),
            ],
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('association', models.CharField(max_length=100)),
                ('organisation', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
            ],
        ),
    ]
