# Generated by Django 5.0.4 on 2024-05-08 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_page8_referee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageModel8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_papers', models.FileField(upload_to='research_papers')),
                ('phd_certificate', models.FileField(upload_to='phd_certificate')),
                ('pg_documents', models.FileField(upload_to='pg_documents')),
                ('ug_documents', models.FileField(upload_to='ug_documents')),
                ('certificate_12th', models.FileField(upload_to='certificate_12th')),
                ('certificate_10th', models.FileField(upload_to='certificate_10th')),
                ('pay_slip', models.FileField(upload_to='pay_slip')),
                ('noc_undertaking', models.FileField(upload_to='noc_undertaking')),
                ('post_phd_experience', models.FileField(upload_to='post_phd_experience')),
                ('other_documents', models.FileField(upload_to='other_documents')),
                ('signature', models.ImageField(upload_to='signature')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Page8',
        ),
    ]
